title: Beginner Scratch Sushi Cards
hero_image: images/banner.png
description: Make your first Scratch program!
theme: orange # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
curriculum: 0, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: animals, art, humour, space, photography, outdoors, music, games
technologies: scratch
site_areas: coderdojo
hardware: electronic-components, sense-hat
software: scratch
version: 1
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Getting set up
- title: Adding & removing code
- title: Setting the scene
- title: Moving things around
- title: All the sprites
- title: Remote-control mosquito
- title: Let's catch some flies!
- title: Keeping score
