---
title: Mosquito patrol
hero_image: images/banner.png
description: Make your first Scratch program!
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: scratch
site_areas: coderdojo, projects
hardware: ''
software: scratch
version: 3.0.0
last_tested: 2018-05-01
steps:
- title: Introduction
  completion: engaged
- title: Getting set up
- title: Adding & removing code
- title: Setting the scene
- title: Moving things around
- title: All the sprites
- title: Remote-control mosquito
- title: Let's catch some mosquitoes!
  completion: internal
- title: Keeping score
- title: 'Challenge: winning the game'
  challenge: true
