---
title: Patrulla de mosquitos
hero_image: images/banner.png
description: "¡Crea tu primer programa de Scratch!"
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: scratch
site_areas: coderdojo, projects
hardware: ''
software: scratch
version: 3.0.0
last_tested: 2018-05-01
steps:
- title: Introducción
- title: Preparación
- title: Agregar y quital el código
  completion:
  - engaged
- title: Configurando el escenario
- title: Moviendo las cosas
- title: Todos los objetos
- title: Mosquito a control remoto
- title: "¡Atrapemos algunos mosquitos!"
- title: Guardando la puntuación
  completion:
  - internal
- title: 'Desafío: Ganar el juego'
  challenge: true
