---
title: Patrouille des moustiques
hero_image: images/banner.png
description: Créer ton premier programme Scratch !
theme: orange #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: ''
interests: ''
technologies: scratch
site_areas: coderdojo, projects
hardware: ''
software: scratch
version: 3.0.0
last_tested: 2018-05-01
steps:
  - 
    title: Introduction
  - 
    title: Mise en place
  - 
    title: Ajouter et supprimer du code
  - 
    title: Préparer la scène
  - 
    title: Déplacer des objets
  - 
    title: Tous les sprites
  - 
    title: Moustique contrôlé à distance
  - 
    title: Attrapons des moustiques !
  - 
    title: Garder le score
  - 
    title: "Défi : gagner la partie"
    challenge: true
